DROP TABLE IF EXISTS "TEMP_HISTORICAL_DATA_{{run_id}}";
CREATE TABLE IF NOT EXISTS "TEMP_HISTORICAL_DATA_{{run_id}}"(
    SYMBOL TEXT,
    TIMESTAMP DATE,
    OPEN NUMERIC,
    HIGH NUMERIC,
    LOW NUMERIC,
    CLOSE NUMERIC,
    VOLUME NUMERIC,
    TRADE_COUNT NUMERIC,
    VWAP NUMERIC,
    INSERT_ID TEXT,
    UPDATE_ID TEXT,
    PRIMARY KEY (SYMBOL, TIMESTAMP)
)