CREATE TABLE IF NOT EXISTS HISTORICAL_DATA(
    SYMBOL TEXT,
    TIMESTAMP DATE,
    OPEN NUMERIC,
    HIGH NUMERIC,
    LOW NUMERIC,
    CLOSE NUMERIC,
    VOLUME NUMERIC,
    TRADE_COUNT NUMERIC,
    VWAP NUMERIC,
    PRIMARY KEY (SYMBOL, TIMESTAMP)
)